resolver: lts-14.6
packages:
- '.'
extra-deps:
- git: https://github.com/purebred-mua/purebred-email
  commit: 7655864d1997eb9660d518fcca3bfe213180abcc
- concise-0.1.0.1
flags: {}
extra-package-dbs: []
nix:
  enable: true
  packages:
    - git
    - zlib
    - ssmtp
