resolver: lts-16.31
packages:
- '.'
extra-deps:
# - git: https://github.com/purebred-mua/purebred-email
#   commit: a37730d790fbc6e0611764728fb6c08b14801e75
- ../purebred-email
- git: "https://github.com/talanis85/disguise.git"
  commit: "8840e025f34469efd930f461a39a8d7177660626"
- git: "https://github.com/talanis85/disguise-gtk.git"
  commit: "7d16df0c9f830accc28374455c6897f57e50df95"
- concise-0.1.0.1
- wl-pprint-1.2.1
- cairo-0.13.8.1
- gio-0.13.8.1
- glib-0.13.8.1
- gtk2hs-buildtools-0.13.8.0
- gtk3-0.15.5
- pango-0.13.8.1
flags: {}
extra-package-dbs: []
nix:
  enable: true
  packages:
    - git
    - zlib
    - ssmtp
    - icu
    - cairo
    - gnome3.gtk
    - pango
    - pkgconfig
    - xlibs.xorgproto
    - xorg.libX11
