resolver: lts-14.6
packages:
- '.'
extra-deps:
- git: https://github.com/purebred-mua/purebred-email
  commit: aeb30b4219cdef75107755e11803cd44f00d0087
- concise-0.1.0.1
- wl-pprint-1.2.1
flags: {}
extra-package-dbs: []
nix:
  enable: true
  packages:
    - git
    - zlib
    - ssmtp
