resolver: lts-8.24
packages:
- '.'
- ../purebred-email
extra-deps:
- mime-0.4.0.2
# - purebred-email-0.1.0.1
- concise-0.1.0.1
flags: {}
extra-package-dbs: []
nix:
  enable: true
  shell-file: stack.nix
